name: money_hooks
description: MoneyHooksMobile

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  switcher: ^1.0.0
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  flutter_riverpod: ^3.0.3
  flutter_launcher_icons: ^0.14.2
  loading_animation_widget: ^1.2.0+3
  dio: ^5.3.3
  loader_overlay: ^5.0.0
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  sign_in_button: ^4.0.1
  shared_preferences: ^2.2.2
  localstore: ^1.3.5
  flutter_slidable: ^4.0.0
  crypto: ^3.0.2
  fl_chart: ^1.0.0
  firebase_remote_config: ^6.0.0
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  go_router: ^17.0.1
  provider: ^6.1.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/moneyhookicon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - "images/"
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: MPLUS1p
      fonts:
        - asset: assets/fonts/MPLUS1p.ttf
          weight: 300
    - family: DotGothic16
      fonts:
        - asset: assets/fonts/DotGothic16.ttf
          weight: 300
    - family: NotoSansJP-Regular
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 300
    - family: MoneyBill
      fonts:
        - asset: assets/icons/MoneyBill.ttf
    - family: QuestionCircleO
      fonts:
        - asset: assets/icons/QuestionCircleO.ttf
    - family: Dollar
      fonts:
        - asset: assets/icons/Dollar.ttf
    - family: Wallet
      fonts:
        - asset: assets/icons/Wallet.ttf
    - family: Dot
      fonts:
        - asset: assets/icons/Dot.ttf